version: "3"
services:
  db:
    container_name: "db-nestjs-migrations-seeding"
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: "pass123"